name: build

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ${{ env.BUILD_RUNS_ON || 'ubuntu-latest' }}
    steps:
    - uses: actions/checkout@v3
    - run: echo "Will run on ${{ env.BUILD_RUNS_ON || 'ubuntu-latest' }}"
