name: build

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ${{ vars.BUILD_RUNS_ON || (github.repository == 'jluebbe/runner-test' && 'custom') || 'ubuntu-latest' }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup SSH Key for Yocto Cache
      if: ${{ secrets.YOCTO_CACHE_KEY }}
      run: |
        echo "${{ secrets.YOCTO_CACHE_KEY }}" >> ~/.ssh/id_ed25519
    - name: Create Data
      run: |
        touch foo
    - name: Cache Data
      if ${{ secrets.YOCTO_CACHE_KEY && !cancelled() }}
      run: |
        rsync -avxP ./ 10.0.2.2:yocto-cache/
