name: build

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ${{ vars.BUILD_RUNS_ON || (github.repository == 'jluebbe/runner-test' && 'custom') || 'ubuntu-latest' }}
    steps:
    - uses: actions/checkout@v3
    - run: echo "Will run on ${{ vars.BUILD_RUNS_ON || 'ubuntu-latest' }}"
